---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>
  network:
    - ["forwarded_port", {guest: 8000, host: 58000}]
    - ["forwarded_port", {guest: 8080, host: 58080}]

transport:
  name: sftp

driver_config:
    customize:
#      cpus: 2
      memory: 2048

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  name: chef_solo

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
#  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:

