---
driver:
  name: lxd_cli

transport:
  name: sftp

driver_config:
    customize:
#      cpus: 2
      memory: 2048

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
#  - name: ubuntu-14.04
  - name: centos-7
#    provisioner:
## FIXME!/workaround: virtualenv bug in 2.2: https://github.com/ansible/ansible-modules-core/issues/5470
#      ansible_version: 2.1.2.0
#  - name: centos-6
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:

