---

- name: create grr datastore in mysql
  mysql_db: "name={{ grr_datastore_mysql_db }} state=present"

- name: create grr datastore user in mysql
  mysql_user:
    name: "{{ grr_datastore_mysql_user }}"
    password: "{{ grr_datastore_mysql_pass }}"
    priv: "{{ grr_datastore_mysql_db }}.*:ALL"
    state: present
