---

##  grr/scripts/install_script_ubuntu.sh: BUILD_DEPS_ONLY
#- command: add-apt-repository ppa:gift/dev -y
- apt_repository: repo='ppa:gift/dev'

#- name: upgrade packages
#  apt: upgrade=safe update_cache=yes
#  async: 3600
#  poll: 300

- stat: path=/root/{{ grr_debarchive_url | basename }}
  register: grrdeb
- name: Download Grr deb archive
  get_url: url="{{ grr_debarchive_url }}"
    dest="/root/{{ grr_debarchive_url | basename }}"
    mode=0400
#    sha256sum=9f8f38bda19557e91086022cea473fbffe0e113027ebae4f4d592772ba4d291d
  when: not grrdeb.stat.exists
- name: apt | grr dependencies install
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - software-properties-common
    - apache2-utils
    - build-essential
    - debhelper
    - dpkg-dev
    - git-core
    - ipython
    - libdistorm64-dev
    - libdistorm64-1
    - libfreetype6-dev
    - libpng-dev
    - libprotobuf-dev
    - ncurses-dev
    - pkg-config
    - prelink
    - protobuf-compiler
    - python-m2crypto
    - python-protobuf
    - python-setuptools
    - python-support
    - python-pip
    - libpython-dev
    - python-dev
## No package matching 'pytsk3' is available
#    - pytsk3
    - python-pytsk3
    - rpm
    - sleuthkit
    - swig
    - wget
    - zip

- name: apt | Mysql datastore dependencies
  apt: name={{item}} state=present
  with_items:
    - mysql-server-5.6
    - python-mysqldb
  when: grr_datastore is defined and grr_datastore == 'MysqlAdvanced' and grr_datastore_mysql_host == 'localhost'

- name: apt | Ensure Mysql is running and enabled on boot.
  service: name=mysql state=started enabled=yes
  when: grr_datastore is defined and grr_datastore == 'MysqlAdvanced' and grr_datastore_mysql_host == 'localhost'

- name: apt | install GRR server
  apt: deb="/root/{{ grr_debarchive_url | basename }}"

