---

##  grr/scripts/install_script_ubuntu.sh: BUILD_DEPS_ONLY
#- command: add-apt-repository ppa:gift/dev -y
- name: install ppa gift - dev
  apt_repository: repo='ppa:gift/dev'

- name: apt | grr dependencies install
  apt: name={{ grrserver_pkg }} state=present update_cache=yes
  register: pkg_result
  until: pkg_result is success

## Why travis got 'Depends: mysql-client-5.6 (>= 5.6.28-0ubuntu0.14.04.1) but it is not going to be installed'
##      and kitchen is fine... = try switching to 5.5
- name: Verify available mysql-client
  command: 'apt-cache search mysql-client'
  register: d1
  changed_when: false
- debug: var=d1.stdout_lines

- name: apt | Mysql datastore dependencies
  apt:
    name: "{{ grr_datastore_mysql_pkg }}"
    state: present
  when: grr_datastore is defined and grr_datastore == 'MysqlAdvanced' and grr_datastore_mysql_host == 'localhost'
  register: pkg_result
  until: pkg_result is success

- name: apt | Ensure Mysql is running and enabled on boot.
  service: name=mysql state=started enabled=yes
  when: grr_datastore is defined and grr_datastore == 'MysqlAdvanced' and grr_datastore_mysql_host == 'localhost'

- block:
    - name: Check if Grr deb archive is present
      stat: path=/root/{{ grr_debarchive_url | basename }}
      register: grrdeb
    - name: Download Grr deb archive
      get_url: url="{{ grr_debarchive_url }}"
        dest="/root/{{ grr_debarchive_url | basename }}"
        mode=0400
        checksum="sha256:{{ grr_debarchive_hash }}"
      when: not grrdeb.stat.exists
    - name: apt | install GRR server
      apt: deb="/root/{{ grr_debarchive_url | basename }}"
      register: pkg_result
      until: pkg_result is success
    - name: Xenial | set facts for grr
      set_fact:
        grr_bindir: /usr/bin
        grr_etc: /etc/grr
        grr_executables: /usr/share/grr-server/executables/
  when: ansible_distribution_release == 'xenial'

#- include: source-build.yml
- include: grr-pip.yml
  when: ansible_distribution_release != 'xenial'
