---

## https://fedoraproject.org/wiki/EPEL
## Failed to validate the SSL certificate for getfedora.org:443. https://github.com/ansible/ansible/issues/12161
## meantime: use hash + no cert validation
- set_fact:
    epel_rpm_key: 'https://getfedora.org/static/0608B895.txt'
    epel_rpm_key_hash: 16d35fa467c6efcee21d3aa068a02054b6a89a7a33bffa94db1fc141693d62a3
  when: ansible_distribution_major_version == "6"
- set_fact:
    epel_rpm_key: 'https://getfedora.org/static/352C64E5.txt'
    epel_rpm_key_hash: 22f25ad95d5e8d371760815485dba696ea3002fc2c7f812f2c75276853387107
  when: ansible_distribution_major_version == "7"

- stat: path="/var/tmp/{{ epel_rpm_key | basename }}"
  register: epelkey
- name: Download epel rpm key
  get_url: "url={{ epel_rpm_key }} dest=/var/tmp/{{ epel_rpm_key | basename }} mode=0600 checksum=sha256:{{ epel_rpm_key_hash }} validate_certs=no"
  when: not epelkey.stat.exists
- name: Installing epel rpm key
#  rpm_key: key={{ epel_rpm_key }}
  rpm_key: key=/var/tmp/{{ epel_rpm_key | basename }}
           state=present

## FIXME! ansible not detecting package already installed if http
- name: check if epel installed
  command: rpm -q epel-release
  register: rpmepel
  changed_when: false
  ignore_errors: true
- name: RedHat6 | Install Fedora epel
  yum: name=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
       state=present
  when: ansible_distribution_major_version == "6" and rpmepel.rc != 0
- name: RedHat7 | Install Fedora epel
  yum: name=https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
       state=present
  when: ansible_distribution_major_version == "7" and rpmepel.rc != 0

