---

- name: generate keys
  command: "{{ grr_bindir }}/grr_config_updater generate_keys --overwrite"
  ignore_errors: true

- name: restart grr-server - systemd
  service: name=grr-server state=restarted
  when: ansible_distribution_release == 'xenial'

- name: restart grr
  service: name={{ item }} state=restarted
  with_items:
    - grr-dataserver-master
    - grr-http-server
    - grr-worker
    - grr-dataserver-slave
    - grr-ui
  when: ansible_distribution_release != 'xenial'

- name: systemd reload
  systemd:
    daemon_reload: yes
